### ISSUE TITLE
tagName.toLowerCase is not a function issue

### ISSUE THREAD

**Issue by chengz** [schomery/popup-blocker#66]
When running a ember application with the addon enabled, it produces a tagName.toLowerCase is not a function js error. See screenshot below.
![image](https://user-images.githubusercontent.com/960322/33700429-57af740c-db6d-11e7-8f3d-da445dbfcc9e.png)

The simplest way to fix this is to use toString() before calling toLowerCase() I think.

**Comment by schomery** [comment]
do you have an example page. I want to check this before releasing 0.5.0

**Comment by swinston1000** [comment]
Hi

I seem to have this same issue in my Ember app (Ember ver 2.51)

I am using popup blocker 4.0.8.3 with the latest version of chrome  (72.0)

```
tagName.toLowerCase is not a function
  at HTMLDocument.document.createElement (<anonymous>:357:28)
  at i.s.createElementNS.w.createElement [as createElement] (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:1096:96)
  at Object.buildFragment (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3535:9)
  at l (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3551:70)
  at Function.s.build (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3551:270)
  at e.default (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3528:9)
  at https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3637:1
  at a (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3625:7)
  at i._firstRender (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3635:104)
  at i.invoke (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3632:301)
  at m.<anonymous> (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:1532:92)
  at Object.e.instrument (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:1587:168)
  at m.render (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:1531:10)
  at Object.e.default (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:1305:15)
  at x (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3465:41)
  at Object.S [as inline] (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3481:173)
  at Object.inline (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3515:39)
  at s.populateNodes (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3557:16)
  at s.render (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3552:446)
  at Object.e.default (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3529:10)
  at Object.yield (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3445:10)
  at r (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:1259:12)
  at n.e.ifHelper [as helper] (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:1260:54)
  at n.compute (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:1565:180)
  at n.value (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:2157:120)
  at Object.e.default [as invokeHelper] (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:1349:62)
  at https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3462:16
  at Object.a [as renderAndCleanup] (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3625:7)
  at _ (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3463:3)
  at k (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3461:118)
  at Object.w [as block] (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3461:67)
  at Object.block (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3514:39)
  at s.populateNodes (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3555:82)
  at s.render (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3552:446)
  at e.default (https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3529:10)
  at https://qa-e.optibus.co/assets/vendor-d7b75d0697f195efec0804e8cc6c03a7.js:3637:1
```
